services:
  postgres:
    image: postgres:16
    container_name: agrosoft-postgres
    environment:
      POSTGRES_DB: agrosoft
      POSTGRES_USER: agrosoft
      POSTGRES_PASSWORD: agrosoft
    ports:
      - "5433:5432"
    volumes:
      - agrosoft-postgres-data:/var/lib/postgresql/data

volumes:
  agrosoft-postgres-data:
  