spring.application.name=AgroSoft

spring.datasource.url=jdbc:postgresql://localhost:5433/agrosoft
spring.datasource.username=agrosoft
spring.datasource.password=agrosoft

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true