spring.application.name=AgroSoft

spring.datasource.url=jdbc:postgresql://localhost:5432/agrosoft
spring.datasource.username=agrosoft
spring.datasource.password=agrosoft

sping.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
